name: C/C++ CI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake -S . -B Build
    - name: make
      run: make -C Build
    - name: run tests
      run: ./Build/2025-05-27